import Head from "next/head";
import Image from "next/image";
import Stage from "./components/stage";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next 23232</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stage />
    </div>
  );
}
